name: simplestreams
description: |
  Simple Streams describe streams of like items in a structural fashion.
  A client provides a way to sync or act on changes in a remote stream.
homepage: https://launchpad.net/simplestreams/
repository: https://github.com/canonical/simplestreams.dart
issue_tracker: https://github.com/canonical/simplestreams.dart/issues
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  equatable: ^2.0.5
  intl: ^0.18.0
  json_annotation: ^4.5.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  lints: ^2.0.1
  mockito: 5.3.2
  test: ^1.21.1
